books = [
    ["1984", "George Orwell", 1949],
    ["Animal Farm", "George Orwell", 1945],
    ["To Kill a Mockingbird", "Harper Lee", 1960],
    ["Pride and Prejudice", "Jane Austen", 1813],
    ["The Great Gatsby", "F. Scott Fitzgerald", 1925],
    ["War and Peace", "Leo Tolstoy", 1869],
    ["The Hobbit", "J.R.R. Tolkien", 1937],
    ["Crime and Punishment", "Fyodor Dostoevsky", 1866],
    ["Brave New World", "Aldous Huxley", 1932],
    ["Wuthering Heights", "Emily Brontë", 1847],
    ["Jane Eyre", "Charlotte Brontë", 1847],
    ["The Picture of Dorian Gray", "Oscar Wilde", 1890],
    ["Fahrenheit 451", "Ray Bradbury", 1953],
    ["Don Quixote", "Miguel de Cervantes", 1605],
    ["The Alchemist", "Paulo Coelho", 1988],
    ["One Hundred Years of Solitude", "Gabriel García Márquez", 1967],
    ["Dracula", "Bram Stoker", 1897],
    ["The Kite Runner", "Khaled Hosseini", 2003],
    ["The Brothers Karamazov", "Fyodor Dostoevsky", 1880],
    ["The Adventures of Huckleberry Finn", "Mark Twain", 1884],
    ["Les Misérables", "Victor Hugo", 1862],
    ["The Old Man and the Sea", "Ernest Hemingway", 1952],
    ["A Tale of Two Cities", "Charles Dickens", 1859],
    ["The Catcher in the Rye", "J.D. Salinger", 1951],
    ["The Lord of the Rings", "J.R.R. Tolkien", 1954],
    ["Le Petit Prince", "Antoine de Saint-Exupéry", 1943],
    ["Harry Potter and the Sorcerer's Stone", "J.K. Rowling", 1997]
]

